<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvincesSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('provinces')->delete();

        DB::table('provinces')->insert(array(
            0 =>
            array(
                'id' => 1,
                'prov_id' => 11,
                'prov_name' => 'ACEH',
                'map_name' => 'Aceh',
                'simple_name' => 'Aceh',
                'lat' => '4.695135',
                'long' => '96.7493993',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array(
                'id' => 2,
                'prov_id' => 12,
                'prov_name' => 'SUMATERA UTARA',
                'map_name' => 'Sumatera Utara',
                'simple_name' => 'SumUt',
                'lat' => '2.1153547',
                'long' => '99.5450974',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array(
                'id' => 3,
                'prov_id' => 13,
                'prov_name' => 'SUMATERA BARAT',
                'map_name' => 'Sumatera Barat',
                'simple_name' => 'SumBar',
                'lat' => '-0.7399397',
                'long' => '100.8000051',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array(
                'id' => 4,
                'prov_id' => 14,
                'prov_name' => 'RIAU',
                'map_name' => 'Riau',
                'simple_name' => 'Riau',
                'lat' => '0.2933469',
                'long' => '101.7068294',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array(
                'id' => 5,
                'prov_id' => 15,
                'prov_name' => 'JAMBI',
                'map_name' => 'Jambi',
                'simple_name' => 'Jambi',
                'lat' => '-1.6101229',
                'long' => '103.6131203',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array(
                'id' => 6,
                'prov_id' => 16,
                'prov_name' => 'SUMATERA SELATAN',
                'map_name' => 'Sumatera Selatan',
                'simple_name' => 'SumSel',
                'lat' => '-3.3194374',
                'long' => '103.914399',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array(
                'id' => 7,
                'prov_id' => 17,
                'prov_name' => 'BENGKULU',
                'map_name' => 'Bengkulu',
                'simple_name' => 'Bengkulu',
                'lat' => '-3.7928451',
                'long' => '102.2607641',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array(
                'id' => 8,
                'prov_id' => 18,
                'prov_name' => 'LAMPUNG',
                'map_name' => 'Lampung',
                'simple_name' => 'Lampung',
                'lat' => '-4.5585849',
                'long' => '105.4068079',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array(
                'id' => 9,
                'prov_id' => 19,
                'prov_name' => 'KEPULAUAN BANGKA BELITUNG',
                'map_name' => 'Kepulauan Bangka Belitung',
                'simple_name' => 'KepBaBel',
                'lat' => '-2.7410513',
                'long' => '106.4405872',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array(
                'id' => 10,
                'prov_id' => 21,
                'prov_name' => 'KEPULAUAN RIAU',
                'map_name' => 'Kepulauan Riau',
                'simple_name' => 'KepRiau',
                'lat' => '3.9456514',
                'long' => '108.1428669',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array(
                'id' => 11,
                'prov_id' => 31,
                'prov_name' => 'DKI JAKARTA',
                'map_name' => 'Daerah Khusus Ibukota Jakarta',
                'simple_name' => 'DKIJ',
                'lat' => '-6.1944491',
                'long' => '106.8229198',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array(
                'id' => 12,
                'prov_id' => 32,
                'prov_name' => 'JAWA BARAT',
                'map_name' => 'Jawa Barat',
                'simple_name' => 'JaBar',
                'lat' => '-7.090911',
                'long' => '107.668887',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array(
                'id' => 13,
                'prov_id' => 33,
                'prov_name' => 'JAWA TENGAH',
                'map_name' => 'Jawa Tengah',
                'simple_name' => 'JaTeng',
                'lat' => '-7.150975',
                'long' => '110.1402594',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array(
                'id' => 14,
                'prov_id' => 34,
                'prov_name' => 'DAERAH ISTIMEWA YOGYAKARTA',
                'map_name' => 'Daerah Istimewa Yogyakarta',
                'simple_name' => 'DIY',
                'lat' => '-7.8753849',
                'long' => '110.4262088',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array(
                'id' => 15,
                'prov_id' => 35,
                'prov_name' => 'JAWA TIMUR',
                'map_name' => 'Jawa Timur',
                'simple_name' => 'JaTim',
                'lat' => '-7.5360639',
                'long' => '112.2384017',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array(
                'id' => 16,
                'prov_id' => 36,
                'prov_name' => 'BANTEN',
                'map_name' => 'Banten',
                'simple_name' => 'Banten',
                'lat' => '-6.4058172',
                'long' => '106.0640179',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array(
                'id' => 17,
                'prov_id' => 51,
                'prov_name' => 'BALI',
                'map_name' => 'Bali',
                'simple_name' => 'Bali',
                'lat' => '-8.4095178',
                'long' => '115.188916',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array(
                'id' => 18,
                'prov_id' => 52,
                'prov_name' => 'NUSA TENGGARA BARAT',
                'map_name' => 'Nusa Tenggara Barat',
                'simple_name' => 'NTB',
                'lat' => '-8.6529334',
                'long' => '117.3616476',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array(
                'id' => 19,
                'prov_id' => 53,
                'prov_name' => 'NUSA TENGGARA TIMUR',
                'map_name' => 'Nusa Tenggara Timur',
                'simple_name' => 'NTT',
                'lat' => '-8.6573819',
                'long' => '121.0793705',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array(
                'id' => 20,
                'prov_id' => 61,
                'prov_name' => 'KALIMANTAN BARAT',
                'map_name' => 'Kalimantan Barat',
                'simple_name' => 'KalBar',
                'lat' => '-0.2787808',
                'long' => '111.4752851',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array(
                'id' => 21,
                'prov_id' => 62,
                'prov_name' => 'KALIMANTAN TENGAH',
                'map_name' => 'Kalimantan Tengah',
                'simple_name' => 'KalTeng',
                'lat' => '-1.6814878',
                'long' => '113.3823545',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array(
                'id' => 22,
                'prov_id' => 63,
                'prov_name' => 'KALIMANTAN SELATAN',
                'map_name' => 'Kalimantan Selatan',
                'simple_name' => 'KalSel',
                'lat' => '-3.0926415',
                'long' => '115.2837585',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array(
                'id' => 23,
                'prov_id' => 64,
                'prov_name' => 'KALIMANTAN TIMUR',
                'map_name' => 'Kalimantan Timur',
                'simple_name' => 'KalTim',
                'lat' => '0.5386586',
                'long' => '116.419389',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array(
                'id' => 24,
                'prov_id' => 65,
                'prov_name' => 'KALIMANTAN UTARA',
                'map_name' => 'Kalimantan Utara',
                'simple_name' => 'KalUt',
                'lat' => '3.0730929',
                'long' => '116.0413889',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array(
                'id' => 25,
                'prov_id' => 71,
                'prov_name' => 'SULAWESI UTARA',
                'map_name' => 'Sulawesi Utara',
                'simple_name' => 'SulUt',
                'lat' => '0.6246932',
                'long' => '123.9750018',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array(
                'id' => 26,
                'prov_id' => 72,
                'prov_name' => 'SULAWESI TENGAH',
                'map_name' => 'Sulawesi Tengah',
                'simple_name' => 'SulTeng',
                'lat' => '-1.4300254',
                'long' => '121.4456179',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array(
                'id' => 27,
                'prov_id' => 73,
                'prov_name' => 'SULAWESI SELATAN',
                'map_name' => 'Sulawesi Selatan',
                'simple_name' => 'SulSel',
                'lat' => '-3.6687994',
                'long' => '119.9740534',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array(
                'id' => 28,
                'prov_id' => 74,
                'prov_name' => 'SULAWESI TENGGARA',
                'map_name' => 'Sulawesi Tenggara',
                'simple_name' => 'SulTenggara',
                'lat' => '-1.8479',
                'long' => '120.5279',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array(
                'id' => 29,
                'prov_id' => 75,
                'prov_name' => 'GORONTALO',
                'map_name' => 'Gorontalo',
                'simple_name' => 'Gorontalo',
                'lat' => '0.5435442',
                'long' => '123.0567693',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array(
                'id' => 30,
                'prov_id' => 76,
                'prov_name' => 'SULAWESI BARAT',
                'map_name' => 'Sulawesi Barat',
                'simple_name' => 'SulBar',
                'lat' => '-2.8441371',
                'long' => '119.2320784',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array(
                'id' => 31,
                'prov_id' => 81,
                'prov_name' => 'MALUKU',
                'map_name' => 'Maluku',
                'simple_name' => 'Maluku',
                'lat' => '-3.2384616',
                'long' => '130.1452734',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array(
                'id' => 32,
                'prov_id' => 82,
                'prov_name' => 'MALUKU UTARA',
                'map_name' => 'Maluku Utara',
                'simple_name' => 'MalUt',
                'lat' => '1.5709993',
                'long' => '127.8087693',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array(
                'id' => 33,
                'prov_id' => 91,
                'prov_name' => 'PAPUA',
                'map_name' => 'Papua',
                'simple_name' => 'Papua',
                'lat' => '-4.269928',
                'long' => '138.0803529',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array(
                'id' => 34,
                'prov_id' => 92,
                'prov_name' => 'PAPUA BARAT',
                'map_name' => 'Papua Barat',
                'simple_name' => 'PaBar',
                'lat' => '-1.3361154',
                'long' => '133.1747162',
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array(
                'id' => 35,
                'prov_id' => 93,
                'prov_name' => 'PAPUA SELATAN',
                'map_name' => 'Papua Selatan',
                'simple_name' => 'PaSel',
                'lat' => null,
                'long' => null,
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array(
                'id' => 36,
                'prov_id' => 94,
                'prov_name' => 'PAPUA TENGAH',
                'map_name' => 'Papua Tengah',
                'simple_name' => 'PaTeng',
                'lat' => null,
                'long' => null,
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array(
                'id' => 37,
                'prov_id' => 95,
                'prov_name' => 'PAPUA PEGUNUNGAN',
                'map_name' => 'Papua Pegunungan',
                'simple_name' => 'PaPegunungan',
                'lat' => null,
                'long' => null,
                'locationid' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
    }
}
